#!/usr/bin/perl
use List::Util qw(min);

sub distance {
	my @DP;
	my ($word1, $word2) = @_;
	
	
	for (my $i = 0; $i <= length($word1); $i++) {
		$DP[0][$i] = $i;
	}
	for (my $j = 0; $j <= length($word2); $j++) {
		$DP[$j][0] = $j;
	}
	
	for (my $i = 1; $i <= length($word1); $i++) {
		for (my $j = 1; $j <= length($word2); $j++) {
			my $cost = 0;
			if (substr($word1,$i-1,1) ne substr($word2,$j-1,1)) {
				$cost = 1;
			}

			$DP[$j][$i] = min($DP[$j-1][$i] +1, $DP[$j][$i-1] +1 , $DP[$j-1][$i-1] + $cost);			
			#print $i . " " .$j . " " .$DP[$j][$i] . "\n";
			
		}
	}
	
	return $DP[length($word2)][length($word1)];


}

sub main {
	print "Enter Sentence : ";
	my $dict = "/usr/share/dict/words";
	open(DICT,"$dict") or die "Can't Open Dictionary!";
	my $line = <>;
	my @words = split(/\ /,$line,-1);
	print "Misspelled Word\n=====================\n";

	my $noSpellWrong = 1;

	foreach my $word ( @words ) {
		$word = lc($word);
		chomp($word);
		
		my $minDistance = 1000;
		my @bestlist = ();
		

		my $wordLength = length($word);
		my $isFound = 0;

		while(<DICT>) {

				#Using String length as a simple hash, for fast comparision
				if(abs(length($_)-1-$wordLength) <= $minDistance) {
					$currentWord = lc($_);
					chomp($currentWord);
					$dist = distance($currentWord, $word);
					if ($dist < $minDistance) {
						@bestlist = ();
						$minDistance = $dist;	
					}
					if ($dist == $minDistance) {
						push(@bestlist, $currentWord);
					}
					if ($minDistance == 0) {
						$isFound = 1;
						break;
					}
				}
		}
		if(!$isFound) {
			print "$word : @bestlist\n";
			$noSpellWrong = 0;
		}
		seek(DICT,0,0); #Seek to start of File
	}
	close(DICT);
	if($noSpellWrong) {
		print "No Spelling Mistake Found!\n";
	}
}

main();